import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Hero } from "@/components/home-sections/Hero";
import { Menu } from "@/components/home-sections/Menu";
import { HowWeDo } from "@/components/home-sections/HowWeDo";
import { Testimonial } from "@/components/home-sections/Testimonial";
import { Contact } from "@/components/home-sections/Contact";
import axiosInstance from "@/utilities/axiosInstance";
import { useContext, useEffect } from "react";
import { useGlobalData } from "@/context/context";


const inter = Inter({ subsets: ["latin"] });

export default function Home({company}) {
    console.log(process.env.NEXT_PUBLIC_API_URL)
    const {globalData, setGlobalData} = useGlobalData()
    useEffect(() => {
        setGlobalData({...globalData, company})
    },[company])
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
            <Menu />
            <HowWeDo />
            <Testimonial />
            <Contact />
            {/* <h1 className='bg-orange-500 text-slate-300'>Resto</h1> */}
        </>
    );
}

export async function getStaticProps() {
    const response = await axiosInstance.get('company?populate=*')
    const { data: { attributes = {} }} = response?.data ?? {}
    return {
        props: {
            company: attributes
        },
        revalidate: 10
    }
  }